name: Azure Container Apps Deploy abc11

on:
  push:
    branches:
      - main
env:
  containerAppName: demo
  resourceGroup: demo
 

jobs:

  Run-AZ-CLI-Commnds:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      run: |
          az group list --out table
          SUBSCRIPTION_ID=$(az account show -o tsv --query id)
          az group create --name $resourceGroup --location eastus
  
  
  Run-storage-ARM-Template:
      # needs: Run-AZ-CLI-Commnds
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

     
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: demo
          template: ARMTemplate/storagedeploy.json
          parameters: storageAccountType=Standard_LRS

    
        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}


  Run-ACA-ARM-Template:
      # needs: Run-storage-ARM-Template
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: demo
          template: ARMTemplate/ACAdeploy.json
          parameters: ARMTemplate/ACAdeploy_parameters.json
          
    
        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}


  Build-docker-file-and-deploy:
    needs: [Run-storage-ARM-Template,Run-ACA-ARM-Template]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src
          acrName: tinkushuklaregistry
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: $containerAppName
          resourceGroup: $resourceGroup
